server:
  port: 8000
  context-path: /
debug: true
logging:
  level:
    tk.mybatis: DEBUG
  file: logs/erp-system.log
spring:
  datasource:
    name: it_erp
    url: jdbc:mysql://localhost:3306/it_erp
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mapper:
    plugin: tk.mybatis.mapper.generator.MapperPlugin
    Mapper: com.geekcattle.util.CustomerMapperpper
  messages:
    basename: i18n/messages
    cache-seconds: 3600
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1000